apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-challenge-app
  name: devops-challenge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-challenge-app
  strategy: {}
  template:
    metadata:
      labels:
        app: devops-challenge-app
    spec:
      containers:
      - name: devops-challenge-app
        image: gcr.io/mm-iti-cairo-2023/devops-challenge-app-v2:v1.1
        ports:
         - containerPort: 8000
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
