apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-challenge-app
  name: devops-challenge-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-challenge-app
  type: LoadBalancer
